### ISSUE TITLE
Linux: Port 80 permission denied

### ISSUE THREAD

**Issue by poVoq** [networkimprov/mnm-hammer#3]
I get the following error when trying to start the client.
```
mnm-hammer tmtp client v0.7.0 2020.04.20
mainResult: listen tcp :80: bind: permission denied
```
Failing to fully understand why working through the privileged access port 80 is required, this seems like a bad idea in general :)

**Comment by networkimprov** [comment]
Apologies for the delayed reply! Github didn't add this to my Notifications :-/

The Quick Start instructions ask you to run `App`, which uses port 8123: https://mnmnotmail.org/#quick-start

The `App` script also checks for a previous version and offers to update (i.e. import prior data).

If you don't want/need to run `App`, you can specify the port with `$ ./mnm-hammer -http :nnnn`

If you've setup the [mnm TMTP server](https://github.com/networkimprov/mnm) and can share its address, I'd be happy to make an account and correspond with you :-)

EDIT: I'll be posting a server binary for Linux this week.

**Comment by networkimprov** [comment]
I've posted new releases of the [server](https://github.com/networkimprov/mnm/releases) and [client](https://mnmnotmail.org/#quick-start).
